



import java.awt.Desktop;
import java.net.URI;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;


public class login extends javax.swing.JFrame {

    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    
    }
  
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jpmenu = new javax.swing.JLabel();
        jpmenu1 = new javax.swing.JLabel();
        jpmenu2 = new javax.swing.JLabel();
        jpmenu3 = new javax.swing.JLabel();
        jpmenu4 = new javax.swing.JLabel();
        jpmenu5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jpmenu6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jpmenu7 = new javax.swing.JLabel();
        jpmenu8 = new javax.swing.JLabel();
        jpmenu9 = new javax.swing.JLabel();
        jpmenu10 = new javax.swing.JLabel();
        jpmenu11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Multiply_32px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 102, 102));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Operaciones");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 489, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel15)))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 650, 70));

        jpmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/BD_M3.png"))); // NOI18N
        jpmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpmenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenuMouseMoved(evt);
            }
        });
        jpmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpmenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenuMouseExited(evt);
            }
        });
        jPanel1.add(jpmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 170, 150));

        jpmenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/BD_M1.png"))); // NOI18N
        jpmenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpmenu1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu1MouseMoved(evt);
            }
        });
        jpmenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpmenu1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu1MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, 150));

        jpmenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/BD_M2.png"))); // NOI18N
        jpmenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpmenu2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu2MouseMoved(evt);
            }
        });
        jpmenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpmenu2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu2MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 170, 150));

        jpmenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/BD_M4.png"))); // NOI18N
        jpmenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpmenu3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu3MouseMoved(evt);
            }
        });
        jpmenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpmenu3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu3MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 170, 150));

        jpmenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/8.png"))); // NOI18N
        jpmenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpmenu4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu4MouseMoved(evt);
            }
        });
        jpmenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpmenu4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu4MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 170, 150));

        jpmenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/BD_M5.png"))); // NOI18N
        jpmenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpmenu5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu5MouseMoved(evt);
            }
        });
        jpmenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpmenu5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu5MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 170, 150));

        jLabel9.setBackground(new java.awt.Color(0, 102, 102));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Ventas");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 102, 102));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Producto");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 102, 102));
        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Empleados");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 102, 102));
        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Categorias");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        jLabel14.setBackground(new java.awt.Color(0, 102, 102));
        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Clientes");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        jLabel16.setBackground(new java.awt.Color(0, 102, 102));
        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("venta");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));

        jpmenu6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/5.png"))); // NOI18N
        jpmenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpmenu6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu6MouseMoved(evt);
            }
        });
        jpmenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu6MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 70));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 660, -1));

        jpmenu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/12345678.png"))); // NOI18N
        jpmenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpmenu7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu7MouseMoved(evt);
            }
        });
        jpmenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpmenu7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu7MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 80, 70));

        jpmenu8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1234.png"))); // NOI18N
        jpmenu8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpmenu8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu8MouseMoved(evt);
            }
        });
        jpmenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpmenu8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu8MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 80, 70));

        jpmenu9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/12345.png"))); // NOI18N
        jpmenu9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpmenu9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu9MouseMoved(evt);
            }
        });
        jpmenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpmenu9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu9MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 80, 70));

        jpmenu10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/123456.png"))); // NOI18N
        jpmenu10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpmenu10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu10MouseMoved(evt);
            }
        });
        jpmenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpmenu10MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu10MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 80, 70));

        jpmenu11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1234567.png"))); // NOI18N
        jpmenu11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpmenu11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu11MouseMoved(evt);
            }
        });
        jpmenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpmenu11MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu11MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 80, 70));

        jLabel17.setBackground(new java.awt.Color(0, 102, 102));
        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Proveedores");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        jLabel18.setBackground(new java.awt.Color(0, 102, 102));
        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Clasificar");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, 20));

        jLabel19.setBackground(new java.awt.Color(0, 102, 102));
        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Proveer");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, -1, -1));

        jLabel20.setBackground(new java.awt.Color(0, 102, 102));
        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("Detalle de venta");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));

        jLabel21.setBackground(new java.awt.Color(0, 102, 102));
        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("Compra");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
this.setState(login.EXIT_ON_CLOSE);  
int dialog = JOptionPane.YES_NO_OPTION;

int result = JOptionPane.showConfirmDialog(null, "Salir del Punto de venta?", "Exit", dialog);
if (result == 0)
{
    System.exit(0);
}
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
      this.setState(login.ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jpmenu1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu1MouseMoved

      jpmenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10,255,255)));
      
      
        
        
    }//GEN-LAST:event_jpmenu1MouseMoved

    private void jpmenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu1MouseExited
       
    jpmenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245,255,255)));   
        
    }//GEN-LAST:event_jpmenu1MouseExited

    private void jpmenu2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu2MouseMoved
        jpmenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10,255,255)));
    }//GEN-LAST:event_jpmenu2MouseMoved

    private void jpmenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu2MouseExited
     jpmenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245,255,255)));
    }//GEN-LAST:event_jpmenu2MouseExited

    private void jpmenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenuMouseMoved
       jpmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10,255,255)));
    }//GEN-LAST:event_jpmenuMouseMoved

    private void jpmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenuMouseExited
     jpmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245,255,255)));
    }//GEN-LAST:event_jpmenuMouseExited

    private void jpmenu3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu3MouseMoved
       jpmenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10,255,255)));
    }//GEN-LAST:event_jpmenu3MouseMoved

    private void jpmenu3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu3MouseExited
        jpmenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245,255,255)));
    }//GEN-LAST:event_jpmenu3MouseExited

    private void jpmenu4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu4MouseMoved
       jpmenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10,255,255)));
    }//GEN-LAST:event_jpmenu4MouseMoved

    private void jpmenu4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu4MouseExited
        jpmenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245,255,255)));
    }//GEN-LAST:event_jpmenu4MouseExited

    private void jpmenu5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu5MouseMoved
       jpmenu5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10,255,255)));
    }//GEN-LAST:event_jpmenu5MouseMoved

    private void jpmenu5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu5MouseExited
       jpmenu5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245,255,255)));
    }//GEN-LAST:event_jpmenu5MouseExited

    private void jpmenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu1MouseClicked
       ventas venta = new ventas();
      venta.setVisible(true);
      super.dispose();
    }//GEN-LAST:event_jpmenu1MouseClicked

    private void jpmenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu2MouseClicked
      
      producto  prod= new producto();
      prod.setVisible(true);
      super.dispose();
    }//GEN-LAST:event_jpmenu2MouseClicked

    private void jpmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenuMouseClicked
       proveedores  pro= new proveedores();
      pro.setVisible(true);
      super.dispose();
    }//GEN-LAST:event_jpmenuMouseClicked

    private void jpmenu6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu6MouseMoved
       //jpmenu6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10,255,255)));
    }//GEN-LAST:event_jpmenu6MouseMoved

    private void jpmenu6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpmenu6MouseExited

    private void jpmenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu3MouseClicked
     empleados  emple= new empleados();
      emple.setVisible(true);
      super.dispose();
    }//GEN-LAST:event_jpmenu3MouseClicked

    private void jpmenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu5MouseClicked
       categorias  cat= new categorias();
      cat.setVisible(true);
      super.dispose();
    }//GEN-LAST:event_jpmenu5MouseClicked

    private void jpmenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu4MouseClicked
        clientes  clien= new clientes();
     clien.setVisible(true);
      super.dispose();
    }//GEN-LAST:event_jpmenu4MouseClicked

    private void jpmenu7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu7MouseMoved
         jpmenu7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10,255,255)));
    }//GEN-LAST:event_jpmenu7MouseMoved

    private void jpmenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu7MouseClicked
        TD_venta clas = new TD_venta();
     clas.setVisible(true);
    }//GEN-LAST:event_jpmenu7MouseClicked

    private void jpmenu7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu7MouseExited
        
        jpmenu7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245,255,255)));
        
    }//GEN-LAST:event_jpmenu7MouseExited

    private void jpmenu8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu8MouseMoved
        jpmenu8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10,255,255)));
    }//GEN-LAST:event_jpmenu8MouseMoved

    private void jpmenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu8MouseClicked
        TD_clasificar clas = new TD_clasificar();
     clas.setVisible(true);
     
        
        
    }//GEN-LAST:event_jpmenu8MouseClicked

    private void jpmenu8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu8MouseExited
        jpmenu8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245,255,255)));
    }//GEN-LAST:event_jpmenu8MouseExited

    private void jpmenu9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu9MouseMoved
        jpmenu9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10,255,255)));
    }//GEN-LAST:event_jpmenu9MouseMoved

    private void jpmenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu9MouseClicked
        TD_proveer clas = new TD_proveer();
        clas.setVisible(true);
    }//GEN-LAST:event_jpmenu9MouseClicked

    private void jpmenu9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu9MouseExited
          jpmenu9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245,255,255)));
    }//GEN-LAST:event_jpmenu9MouseExited

    private void jpmenu10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu10MouseMoved
         jpmenu10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10,255,255)));
    }//GEN-LAST:event_jpmenu10MouseMoved

    private void jpmenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu10MouseClicked
        TD_detalle_de_venta clas = new TD_detalle_de_venta();
     clas.setVisible(true);
    }//GEN-LAST:event_jpmenu10MouseClicked

    private void jpmenu10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu10MouseExited
          jpmenu10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245,255,255)));
    }//GEN-LAST:event_jpmenu10MouseExited

    private void jpmenu11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu11MouseMoved
      jpmenu11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10,255,255)));
    }//GEN-LAST:event_jpmenu11MouseMoved

    private void jpmenu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu11MouseClicked
        TD_compra clas = new TD_compra();
     clas.setVisible(true);
    }//GEN-LAST:event_jpmenu11MouseClicked

    private void jpmenu11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu11MouseExited
        jpmenu11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245,255,255)));
    }//GEN-LAST:event_jpmenu11MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jpmenu;
    private javax.swing.JLabel jpmenu1;
    private javax.swing.JLabel jpmenu10;
    private javax.swing.JLabel jpmenu11;
    private javax.swing.JLabel jpmenu2;
    private javax.swing.JLabel jpmenu3;
    private javax.swing.JLabel jpmenu4;
    private javax.swing.JLabel jpmenu5;
    private javax.swing.JLabel jpmenu6;
    private javax.swing.JLabel jpmenu7;
    private javax.swing.JLabel jpmenu8;
    private javax.swing.JLabel jpmenu9;
    // End of variables declaration//GEN-END:variables

    private void setIconImage(ImageIcon imageIcon) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
